#!/usr/bin/env python3
from __future__ import annotations
"""Label images under data/ with a local Ollama vision model (qwen3-vl:8b)."""
"""Generated by cursor/auto"""

import argparse
import base64
import io
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from PIL import Image

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".gif"}
DEFAULT_MODEL = "qwen3-vl:8b"
DEFAULT_PROMPT = (
    "Describe this image briefly with a few keywords. "
    "Style examples: concrete building with many windows; blue waterfall; "
    "industrial factory with conveyor belts. "
    "Reply with one short line only."
)


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Label Satisfactory / real-world images via Ollama vision."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=root / "data",
        help="Directory containing source image folders (default: data/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "data" / "labels.json",
        help="Output JSON path (default: data/labels.json)",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"Ollama model name (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--host",
        default="http://127.0.0.1:11434",
        help="Ollama base URL",
    )
    parser.add_argument(
        "--max-side",
        type=int,
        default=768,
        help="Resize longest image side before sending (default: 768)",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Label at most N images (0 = all)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Relabel images even if already present in the output file",
    )
    return parser.parse_args()


def collect_images(data_dir: Path) -> list[Path]:
    images: list[Path] = []
    for path in sorted(data_dir.rglob("*")):
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS:
            images.append(path)
    return images


def encode_image(path: Path, max_side: int) -> str:
    with Image.open(path) as im:
        rgb = im.convert("RGB")
        rgb.thumbnail((max_side, max_side))
        buf = io.BytesIO()
        rgb.save(buf, format="JPEG", quality=80)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def clean_description(text: str) -> str:
    text = text.strip().strip('"').strip("'")
    # Drop accidental leftover think tags if the model leaks them.
    if "</think>" in text:
        text = text.split("</think>", 1)[-1].strip()
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return lines[-1] if lines else text


def label_image(
    path: Path,
    *,
    host: str,
    model: str,
    max_side: int,
    timeout: float = 300.0,
) -> str:
    payload = {
        "model": model,
        "messages": [
            {
                "role": "user",
                "content": DEFAULT_PROMPT,
                "images": [encode_image(path, max_side)],
            }
        ],
        "stream": False,
        # qwen3-vl:8b is a thinking model; give it room to finish reasoning
        # and emit the short description in message.content.
        "options": {
            "num_predict": 1024,
            "temperature": 0.2,
        },
    }
    req = urllib.request.Request(
        f"{host.rstrip('/')}/api/chat",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        data = json.load(resp)

    message = data.get("message") or {}
    content = clean_description(message.get("content") or "")
    if content:
        return content

    # Fallback: some builds only fill thinking; take the last non-empty line.
    thinking = clean_description(message.get("thinking") or "")
    if thinking:
        return thinking

    raise RuntimeError(f"Empty model response for {path}")


def load_existing(output: Path) -> dict[str, dict]:
    if not output.exists():
        return {}
    with output.open(encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, list):
        return {item["filename"]: item for item in data if "filename" in item}
    if isinstance(data, dict) and "images" in data:
        return {
            item["filename"]: item
            for item in data["images"]
            if "filename" in item
        }
    raise ValueError(f"Unrecognized labels format in {output}")


def save_labels(output: Path, by_filename: dict[str, dict]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    images = sorted(by_filename.values(), key=lambda item: item["filename"])
    payload = {
        "model": images[0]["model"] if images else DEFAULT_MODEL,
        "count": len(images),
        "images": images,
    }
    tmp = output.with_suffix(output.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")
    tmp.replace(output)


def main() -> int:
    args = parse_args()
    data_dir: Path = args.data_dir.resolve()
    output: Path = args.output.resolve()

    if not data_dir.is_dir():
        print(f"Data directory not found: {data_dir}", file=sys.stderr)
        return 1

    images = collect_images(data_dir)
    if not images:
        print(f"No images found under {data_dir}", file=sys.stderr)
        return 1

    existing = {} if args.force else load_existing(output)
    pending = [
        path
        for path in images
        if args.force or str(path.relative_to(data_dir)).replace("\\", "/") not in existing
    ]
    if args.limit > 0:
        pending = pending[: args.limit]

    print(
        f"Found {len(images)} images; "
        f"{len(existing)} already labeled; "
        f"{len(pending)} to process with {args.model}"
    )
    if not pending:
        print(f"Nothing to do. Labels at {output}")
        return 0

    by_filename = dict(existing)
    failures = 0
    started = time.time()

    for index, path in enumerate(pending, start=1):
        rel = str(path.relative_to(data_dir)).replace("\\", "/")
        source = path.parent.name
        t0 = time.time()
        try:
            description = label_image(
                path,
                host=args.host,
                model=args.model,
                max_side=args.max_side,
            )
        except (urllib.error.URLError, TimeoutError, RuntimeError, OSError) as exc:
            failures += 1
            print(f"[{index}/{len(pending)}] FAIL {rel}: {exc}", file=sys.stderr)
            continue

        rel_parts = path.relative_to(data_dir).parts
        if "satisfactory" in rel_parts:
            description = f"gmstyle {description}"
        elif "real_world" in rel_parts:
            description = f"rwstyle {description}"

        by_filename[rel] = {
            "filename": rel,
            "source": source,
            "description": description,
            "model": args.model,
        }
        save_labels(output, by_filename)
        elapsed = time.time() - t0
        print(f"[{index}/{len(pending)}] {rel}: {description} ({elapsed:.1f}s)")

    total = time.time() - started
    print(
        f"Done. Wrote {len(by_filename)} labels to {output} "
        f"({failures} failures, {total:.1f}s)"
    )
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())